name: dreamkeys_app
description: "Dream Keys - Sistema Imobili√°rio"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.1
  http: ^1.2.0
  intl: ^0.19.0
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2
  local_auth: ^2.1.7
  image_picker: ^1.1.2
  image_cropper: ^8.0.2
  file_picker: ^8.1.2
  google_fonts: ^6.1.0
  table_calendar: ^3.0.9
  lottie: ^3.0.0
  socket_io_client: ^2.0.3+1
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/loading-home.json
